# Generated by Django 4.0.5 on 2022-11-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_candidateprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='github',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='zipcode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
