# Generated by Django 4.0.5 on 2022-11-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_candidate_education_candidate_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='zipcode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
