# Generated by Django 4.0.5 on 2022-12-01 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
