# Generated by Django 4.0.5 on 2022-12-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='candidates',
            field=models.ManyToManyField(to='users.candidate'),
        ),
    ]
