# Generated by Django 4.1.2 on 2022-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_candidate_id_remove_recruiter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interests',
            field=models.ManyToManyField(to='users.candidate'),
        ),
    ]
