# Generated by Django 4.1.2 on 2022-12-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_offer_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
